version: '3.8'


services: 
    web:
        build: .
        command: python /dfp/manage.py runserver 0.0.0.0:8000
        environment:
            - ENVIRONMENT=production
            - SECRET_KEY=o)bs(jkjsjh4qtq5f(#^f9#@-^b!1u9k1qq@+kuovclk-44xt6
            - DEBUG=0
            - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_J8a1Vc4zClWwtOZIHFbIH7WO00t71bZmHe
            - STRIPE_TEST_SECRET_KEY=sk_test_NLUBdPxcrFJH0MssM1oGvdgZ0063DzF35j
        ports: 
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        environment: 
            POSTGRES_HOST_AUTH_METHOD: "trust"
            
    